import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseDocument } from '../../app/src/parser.js';
import { parseMacros } from '../../app/src/macros.js';
import { buildTexsArchive, parseTexsArchive } from '../../app/src/texs-archive.js';

const ROOT = fileURLToPath(new URL('../..', import.meta.url));
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.woff': 'font/woff',
  '.txt': 'text/plain; charset=utf-8'
};

function createStaticServer(rootDir) {
  return createServer(async (req, res) => {
    try {
      const requestPath = new URL(req.url, 'http://127.0.0.1').pathname;
      const safePath = normalize(requestPath).replace(/^([.][.][\/\\])+/, '');
      let filePath = join(rootDir, safePath);
      if (requestPath.endsWith('/')) filePath = join(rootDir, requestPath, 'index.html');
      const file = await readFile(filePath);
      res.writeHead(200, { 'content-type': MIME[extname(filePath)] ?? 'application/octet-stream' });
      res.end(file);
    } catch {
      res.writeHead(404, { 'content-type': 'text/plain; charset=utf-8' });
      res.end('not found');
    }
  });
}

test('static assets are reachable over HTTP and core roundtrip still works', async () => {
  global.File = class File extends Blob {
    constructor(parts, name, options = {}) {
      super(parts, options);
      this.name = name;
    }
  };
  await stat(join(ROOT, 'app/index.html'));
  await stat(join(ROOT, 'app/vendor/mathjax/es5/tex-chtml-full.js'));

  const server = createStaticServer(ROOT);
  await new Promise((resolve) => server.listen(8876, '127.0.0.1', resolve));

  try {
    const indexRes = await fetch('http://127.0.0.1:8876/app/index.html');
    assert.equal(indexRes.status, 200);
    const html = await indexRes.text();
    assert.match(html, /kakutex-user-manual-ja\.html#disclaimer/);
    assert.match(html, /免責事項を開く/);
    assert.match(html, /vendor\/mathjax\/es5\/tex-chtml-full\.js/);
    assert.match(html, /app\.bundle\.js/);
    assert.match(html, /id="protocol-warning"/);
    assert.match(html, /id="about-dialog"/);
    assert.match(html, /id="about-btn"/);
    assert.match(html, /id="help-btn"/);
    assert.match(html, /KakuTeX/);
    assert.match(html, /macros:\s*\{\s*slashed:\s*\[String\.raw`\{\\not\\!#1\}`,\s*1\]\s*\}/);
    assert.match(html, /inlineMath:\s*\[\['\$', '\$'\], \['\\\\\(', '\\\\\)'\]\]/);

    const cssRes = await fetch('http://127.0.0.1:8876/app/styles.css');
    assert.equal(cssRes.status, 200);
    const css = await cssRes.text();
    assert.ok(!/color\s*:\s*transparent/.test(css));
    assert.match(css, /#body-editor[\s\S]*color:\s*var\(--text\)/);
    assert.match(css, /#body-editor[\s\S]*overflow:\s*auto/);
    assert.match(css, /\.preview-surface[\s\S]*overflow:\s*auto/);
    assert.match(css, /\.about-dialog/);

    const bundleRes = await fetch('http://127.0.0.1:8876/app/app.bundle.js');
    assert.equal(bundleRes.status, 200);
    const bundle = await bundleRes.text();
    assert.doesNotMatch(bundle, /const DEFAULT_BODY = String\.raw`\section\{テスト\}\n\s{4}この節はテスト。/);
    assert.doesNotMatch(bundle, /return String\.raw`% Generated by KakuTeX\n\s{4}\\documentclass/);
    assert.match(bundle, /showSaveFilePicker|downloadBlob/);
    assert.match(bundle, /kakutex-user-manual-(ja|en)\.html/);
    assert.doesNotMatch(bundle, /highlightSource/);

    const manualEnRes = await fetch('http://127.0.0.1:8876/docs/user_manual/kakutex-user-manual-en.html');
    assert.equal(manualEnRes.status, 200);
    const manualEn = await manualEnRes.text();
    assert.match(manualEn, /id="disclaimer"/);
    assert.match(manualEn, /Disclaimer/);

    const manualJaRes = await fetch('http://127.0.0.1:8876/docs/user_manual/kakutex-user-manual-ja.html');
    assert.equal(manualJaRes.status, 200);
    const manualJa = await manualJaRes.text();
    assert.match(manualJa, /id="disclaimer"/);
    assert.match(manualJa, /免責事項/);

    const fontRes = await fetch('http://127.0.0.1:8876/app/vendor/mathjax/output/chtml/fonts/woff-v2/MathJax_Main-Regular.woff');
    assert.equal(fontRes.status, 200);

    const parsedDoc = parseDocument('\\section{Smoke}\nHello $x$.');
    const parsedMacros = parseMacros('\\newcommand{\\Tr}{\\operatorname{Tr}}');
    assert.equal(parsedDoc.blocks.length, 2);
    assert.equal(Object.keys(parsedMacros.macros).length, 1);

    const archive = buildTexsArchive({
      body: 'Hello',
      macros: '\\newcommand{\\Tr}{\\operatorname{Tr}}',
      ui: { locale: 'ja' },
      meta: { fileName: 'smoke.texs' }
    });
    const parsedArchive = await parseTexsArchive(new File([await archive.arrayBuffer()], 'smoke.texs', { type: 'application/zip' }));
    assert.equal(parsedArchive.meta.fileName, 'smoke.texs');
  } finally {
    server.closeIdleConnections?.();
    server.closeAllConnections?.();
    await new Promise((resolve) => server.close(resolve));
  }
});
