import { EXPORT_TEX_NAME } from './config.js';
import { normalizeNewlines, saveBlob } from './utils.js';

function containsJapanese(text) {
  return /[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]/.test(String(text ?? ''));
}

export function buildExportedTex({ body, macros }) {
  const normalizedBody = normalizeNewlines(body).trimEnd();
  const normalizedMacros = normalizeNewlines(macros).trimEnd();
  const macroSection = normalizedMacros ? `${normalizedMacros}\n\n` : '';
  const needsJapanese = containsJapanese(normalizedBody) || containsJapanese(normalizedMacros);
  const japaneseSection = needsJapanese
    ? String.raw`\usepackage{iftex}
\ifLuaTeX
  \IfFileExists{luatexja.sty}{%
    \usepackage{luatexja}
  }{%
    \PackageWarningNoLine{KakuTeX}{Japanese text detected but luatexja.sty was not found}%
  }
\fi
`
    : '';
  const commentBlock = [
    '% Generated by KakuTeX',
    '% Recommended engines:',
    '% - Primary tested path: lualatex exported_file.tex',
    '% - If Japanese text is detected, luatexja is inserted only on the LuaLaTeX path.',
    '% - Alternative DVI path: uplatex exported_file.tex or platex exported_file.tex, then dvipdfmx exported_file.dvi.',
    '% - pxjahyper is not inserted by default. Add it only when you also add hyperref under (u)pLaTeX.'
  ].join('\n');

  return String.raw`${commentBlock}
\documentclass[11pt]{article}
${japaneseSection}\usepackage{amsmath,amssymb,mathtools}
\usepackage{slashed}
\usepackage{geometry}
\geometry{margin=25mm}
${macroSection}\begin{document}
${normalizedBody}
\end{document}
`;
}

export async function exportTexFile(model, fileName = EXPORT_TEX_NAME) {
  const tex = buildExportedTex(model);
  const blob = new Blob([tex], { type: 'text/x-tex;charset=utf-8' });
  return saveBlob(blob, fileName, {
    types: [
      {
        description: 'TeX source',
        accept: {
          'text/x-tex': ['.tex'],
          'text/plain': ['.tex']
        }
      }
    ]
  });
}
